// The GraphQL queries in lib/gh-fetch.js, typechecked against GitHub's schema.
//
// The sandbox cannot POST GraphQL, so these queries have shipped twice without
// ever running (task live-confirm-graphql-queries-7maacy carries that half). But
// the failure that actually happens in this code is a wrong field name or a
// wrong nesting, and that is a typecheck, not a data question: GitHub publishes
// its schema as a static document, so the check is offline and deterministic.
//
// Against a pruned copy of that document (node/graphql/github-schema.pruned.graphql,
// regenerated by `npm run graphql-schema`), which is why this runs in the normal
// suite with no network. The prune is derived from these same queries, so the
// two controls at the bottom are what make the check worth having: they show the
// schema still rejects a field it does not have and an argument left out.
//
// What it cannot answer stays with the live-confirm task: whether messageBody
// holds what we assume, how pagination behaves, whether permissions elide nodes.

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { parse, buildSchema, validate } from 'graphql';
import { repoRoot } from './bootstrap.mjs';

const SCHEMA = path.join(repoRoot, 'node', 'graphql', 'github-schema.pruned.graphql');
const sdl = readFileSync(SCHEMA, 'utf8');
const schema = buildSchema(sdl, { assumeValid: true });

// The documents as the library actually holds them: run gh-fetch.js against a
// stub window and read what it exposes. A query this cannot see is a query
// nothing sends.
const src = readFileSync(path.join(repoRoot, 'lib', 'gh-fetch.js'), 'utf8');
const window = { GH: function GH() {} };
window.GH.prototype = {};
new Function('window', src)(window);
const QUERIES = window.GH.queries;

const errorsFor = doc => validate(schema, parse(doc)).map(e => e.message);

test('lib/gh-fetch.js exposes its query documents by name', () => {
  assert.ok(QUERIES && Object.keys(QUERIES).length >= 3,
    'GH.queries is how a checker reads the documents without sending one');
});

for (const name of Object.keys(window.GH.queries || {})) {
  test(`${name} validates against the published schema`, () => {
    assert.deepEqual(errorsFor(QUERIES[name]), []);
  });

  test(`${name} is the document a method sends`, () => {
    assert.match(src, new RegExp(`QUERIES\\.${name}\\b`),
      'a named query no method references is dead weight the check would bless');
  });
}

test('the pruned schema covers every query, so adding one cannot go unnoticed', () => {
  // The prune is generated FROM these names. A fourth query added without
  // `npm run graphql-schema` may still typecheck by luck, using only fields the
  // slice already carries; the header is what makes the omission loud.
  for (const name of Object.keys(QUERIES)) {
    assert.match(sdl, new RegExp(`^#\\s+${name}$`, 'm'),
      `${name} is not in the pruned schema's header. Run: npm run graphql-schema`);
  }
});

// --- controls: the check has to be able to fail ---

test('control: a field the schema does not have is an error', () => {
  const errors = errorsFor(QUERIES.branchesDated.replace('messageHeadline', 'messageHeadlin'));
  assert.ok(errors.length, 'a misspelled field passed, so this check proves nothing');
  assert.match(errors[0], /messageHeadlin/);
});

test('control: a nesting the schema does not allow is an error', () => {
  // committedDate is a scalar, so selecting into it is exactly the shape mistake
  // this check exists to catch.
  const errors = errorsFor(QUERIES.branchesDated.replace('committedDate', 'committedDate { iso }'));
  assert.ok(errors.length);
  assert.match(errors.join(' '), /committedDate/);
});

test('control: a required argument left out is an error', () => {
  // Kept fields carry their full argument list precisely so this fails.
  const errors = errorsFor(QUERIES.branchesDated.replace('refPrefix:"refs/heads/", ', ''));
  assert.ok(errors.length, 'the pruned schema dropped an argument it should have kept');
  assert.match(errors.join(' '), /refPrefix/);
});
