// ==UserScript==
// @name        wt launcher
// @description The Web Tools launcher and swipe deck
// @match       *://*/*
// @version     c9fa5d3
// @require     https://raw.githubusercontent.com/mehrlander/web-tools/main/userscripts/lib/launcher.js?v=c9fa5d3
// @grant       GM.xmlHttpRequest
// @grant       GM.getValue
// @grant       GM.setValue
// @grant       GM_xmlhttpRequest
// @grant       GM_getValue
// @grant       GM_setValue
// @run-at      document-end
// ==/UserScript==
// Generated by scripts/userscript-stub.py. Pinned to a branch, not a commit,
// and auto-updates from raw so editing the body is a push and never a reinstall.
(async () => {
  const getVal = (typeof GM !== 'undefined' && GM.getValue) ? GM.getValue.bind(GM)
    : (typeof GM_getValue !== 'undefined' ? k => Promise.resolve(GM_getValue(k)) : () => Promise.resolve(null));
  const setVal = (typeof GM !== 'undefined' && GM.setValue) ? GM.setValue.bind(GM)
    : (typeof GM_setValue !== 'undefined' ? (k, v) => Promise.resolve(GM_setValue(k, v)) : () => Promise.resolve());
  const xhr = (typeof GM !== 'undefined' && GM.xmlHttpRequest) ? GM.xmlHttpRequest.bind(GM)
    : (typeof GM_xmlhttpRequest !== 'undefined' ? GM_xmlhttpRequest : null);

  try {
    const cached = await getVal('wt_launcher_code');
    if (cached && cached.includes('window.wtLauncher')) {
      (new Function(cached))();
    }
  } catch (err) {
    console.warn('[wt launcher] dynamic evaluation failed, clearing cache:', err);
    try { await setVal('wt_launcher_code', ''); } catch {}
  }

  if (typeof window.wtLauncher === 'function') {
    window.wtLauncher();
  }

  if (xhr) {
    try {
      const now = Date.now();
      const lastCheck = Number(await getVal('wt_launcher_last_check') || 0);
      if (now - lastCheck > 5 * 60 * 1000) {
        await setVal('wt_launcher_last_check', now);
        xhr({
          method: 'GET',
          url: 'https://raw.githubusercontent.com/mehrlander/web-tools/main/userscripts/builds.json?_=' + now,
          onload: async res => {
            try {
              if (res.status < 200 || res.status >= 300) return;
              const data = JSON.parse(res.responseText);
              const latestBuild = data?.['launcher']?.build;
              const activeBuild = await getVal('wt_launcher_build') || 'c9fa5d3';
              if (latestBuild && latestBuild !== activeBuild) {
                xhr({
                  method: 'GET',
                  url: 'https://raw.githubusercontent.com/mehrlander/web-tools/main/userscripts/lib/launcher.js?_=' + now,
                  onload: async cRes => {
                    if (cRes.status === 200 && cRes.responseText.includes('window.wtLauncher')) {
                      await setVal('wt_launcher_code', cRes.responseText);
                      await setVal('wt_launcher_build', latestBuild);
                    }
                  }
                });
              }
            } catch {}
          }
        });
      }
    } catch {}
  }
})();
