// ==UserScript==
// @name        wt launcher
// @description The Web Tools launcher on pages that have none of their own. Tap for a drawer: what this page is, what it links to, what it says. Collect keeps gathering as you scroll a feed.
// @match       *://*/*
// @require     https://raw.githubusercontent.com/mehrlander/web-tools/main/userscripts/lib/launcher.js
// @run-at      document-end
// ==/UserScript==
// Generated by scripts/userscript-stub.py. Pinned to a branch, not a commit,
// and read from raw rather than a CDN, so editing the body is a push and never
// a reinstall of this file.
window.wtLauncher();
