// export.js — export a page to a portable, self-resolving copy: "download this
// page plus the data it read()s" as one zip, optionally with its code inlined.
//
// read() resolves a path local-first: a <script src=path> sitting beside the
// page (page-relative) wins over the repo copy (root-relative). This kit emits
// the page laid out so that wins with zero manual placement:
//
//   <page-basename>.html      ← page source (baked, if offline), at the zip root
//   <read-path>               ← each read() value, frozen to the local form
//
// Because the HTML is at the zip root, page-relative and bundle-relative
// coincide: a read path like 'data/sample.js' lands at 'data/sample.js' beside
// the HTML, and read('data/sample.js') resolves it local on file://.
//
// Which data? The data the page read()s. gh-boot.js wraps read() to record each
// resolved read on window.__reads, so a page "declares" its data simply by
// reading it. Callers can also pass reads explicitly (opts.reads) — handy when a
// page already holds the value (the cross-repo-read demo does) or wants to export
// data it hasn't read through read() itself.
//
// Two zip modes, differing in exactly one thing: whether THIS REPO's code rides
// along. Both freeze the read() data as sibling files beside the page.
//   default          — code still loads from the CDN. Smaller.
//   { offline:true } — also bakes the gh.load chain in (via build.js).
// "offline" is the flag's name, not a promise: third-party libs (Tailwind,
// daisyUI, Alpine, Phosphor) stay on their CDN tags in BOTH modes, so neither
// zip renders on a machine with no network. What offline:true buys is
// independence from *this repo*, which is what breaks on a private repo, an
// unpushed branch, or a missing token. The FAB labels them "Zip" and
// "Zip + code" for that reason.
//
// renderCopy() is the third output and the odd one out: ONE HTML string, for
// pasting into CodePen or any bare HTML preview. It is not an archive, so it has
// nowhere to put sibling files: the code is inlined the way the offline zip does
// it, and the read() data is inlined too (build.js `data`) rather than laid
// down beside the page. Third-party CDN tags are deliberately left alone, because
// the destination has a network and untouched tags are what make the paste small.
// A page with no gh.load chain at all is already the finished artifact, and comes
// back as its own source with nothing added.
//
// Every entry point takes opts.gh / opts.scripts / opts.reads so a caller can aim
// it at something other than the current window. The FAB does exactly that inside
// a toss, where the page on screen is the subject in the frame and the globals
// belong to the shell around it.
//
// This is the "export" leg of the vocabulary: load → build → bake → export →
// brief. The fifth leg (kits/brief.js) is this kit's reader-facing sibling: it
// drops the boot chain the offline mode has to carry, because a review wants
// the page's own code and nothing else.
(() => {
  // Freeze a read() value into the local deposit form: the file read()'s local
  // probe injects as <script>, which sets document.currentScript.value.
  const localForm = (path, value) =>
    `// ${path} — local form (generated by the export kit). Place beside the\n` +
    `// page so read('${path}') resolves this before the repo copy.\n` +
    `document.currentScript.value = ${JSON.stringify(value, null, 2)};\n`;

  // The page's own repo path. The FAB stamps it on its host element
  // (data-path="pages/foo.html"); fall back to nothing so callers pass opts.path.
  const ownPath = () => document.querySelector('[data-path]')?.dataset.path || '';

  const ensureIo = async () => {
    if (window.io?.saveZip) return;
    if (window.gh?.load) { try { await window.gh.load('kits/io.js'); } catch (e) {} }
    if (!window.io?.saveZip) throw new Error('io.saveZip unavailable (kits/io.js failed to load)');
  };

  const ensureBuildKit = async () => {
    if (window.buildKit) return;
    if (window.gh?.load) { try { await window.gh.load('build.js'); } catch (e) {} }
    if (!window.buildKit) throw new Error('buildKit unavailable (build.js failed to load)');
  };

  // Bake the page's code into the HTML: collect the gh.load chain at runtime,
  // emit the build, and rewrite the gh-api.js import to carry it inline. The
  // result boots with no network (the data files below cover read() the same way).
  const bakeHtml = async (gh, html, opts = {}) => {
    await ensureBuildKit();
    if (!window.buildKit.bakeable(html)) return { html, codeFiles: 0, chainless: true };
    const { ghApiSrc, cache } = await window.buildKit.collectCache(gh, { scripts: opts.scripts });
    const buildJs = window.buildKit.emit({
      ghApiSrc, cache, data: opts.data || null,
      repo: gh.repo || 'mehrlander/web-tools',
      defaultRef: gh.ref || window.__bundleRef || 'main',
    });
    return { html: window.buildKit.bake(html, buildJs), codeFiles: Object.keys(cache).length, chainless: false };
  };

  // Runtime references to this repo's own CDN that survive baking. Inlining
  // covers the gh.load chain, but a page can also reach for our code at run time
  // by other means: the kit demos inject `${base}/kits/<kit>.js` into each proof
  // frame as a plain <script src>, which is not a gh.load and so not in the
  // cache. Those still resolve wherever jsDelivr does, which is the assumption
  // this output makes anyway, but they are exactly what breaks on a private repo
  // or an unpushed branch. Counted, not silently left: a caller can say how much
  // of the page still depends on the network instead of letting a paste discover
  // it. data: URLs are stripped first, or the inlined build would count itself.
  const CDN_REF_RE = /cdn\.jsdelivr\.net\/gh\/mehrlander/g;
  const cdnRefs = html => (html.replace(/data:[^"'`\s)>]+/g, '').match(CDN_REF_RE) || []).length;

  const exporter = {
    localForm,
    cdnRefs,

    // Assemble the file list without downloading — for previews/UI. With
    // opts.offline, the HTML is baked so the zip opens with no network at all
    // (code inlined + data local). Returns
    // { path, base, filename, offline, codeFiles, reads:[paths], files:[{path,data}] }.
    async build(opts = {}) {
      const gh = opts.gh || window.gh;
      if (!gh?.get) throw new Error('window.gh required (gh.get fetches the pristine page source)');

      const path = opts.path || ownPath();
      if (!path) throw new Error('No page path: pass opts.path or set a [data-path] element (the FAB carries it)');

      // Default to the recorded reads; map to the {path,value} shape build needs.
      const reads = opts.reads
        || (window.__reads ? window.__reads.map(r => ({ path: r.path, value: r.value })) : []);
      const scripts = opts.scripts || undefined;

      // Pristine repo copy at the booted ref — not document.documentElement
      // .outerHTML, which is the mutated post-Alpine DOM. On a ?use=<sha> page
      // gh.ref is that sha, so the export captures exactly the version running.
      const { text } = await gh.get(path);
      const base = path.split('/').pop();

      let html = text, codeFiles = 0;
      if (opts.offline) ({ html, codeFiles } = await bakeHtml(gh, text, { scripts }));

      const files = [{ path: base, data: html }];
      for (const { path: p, value } of reads) files.push({ path: p, data: localForm(p, value) });

      const suffix = opts.offline ? '-offline.zip' : '-export.zip';
      const filename = opts.filename || base.replace(/\.html?$/i, '') + suffix;
      return { path, base, filename, offline: !!opts.offline, codeFiles, reads: reads.map(r => r.path), files };
    },

    // One HTML string that renders anywhere with a network: own code inlined,
    // read() data inlined, third-party CDN tags untouched. The output is for
    // pasting, so it is returned rather than downloaded; the caller decides
    // whether that means the clipboard, a file, or a fragment.
    //
    // Returns { html, path, base, codeFiles, reads, dropped, bytes, chainless,
    // cdnRefs }. `chainless` is true when the page had no gh.load chain to
    // inline, which is not a degraded result: that page was already a standalone
    // artifact. `cdnRefs` counts what still reaches for our CDN at run time.
    async renderCopy(opts = {}) {
      const gh = opts.gh || window.gh;
      if (!gh?.get) throw new Error('window.gh required (gh.get fetches the pristine page source)');

      const path = opts.path || ownPath();
      if (!path) throw new Error('No page path: pass opts.path or set a [data-path] element (the FAB carries it)');

      const reads = opts.reads
        || (window.__reads ? window.__reads.map(r => ({ path: r.path, value: r.value })) : []);

      // Only what survives a round trip through JSON can ride inside the file.
      // A value that does not (a live handle, a cyclic object) is dropped rather
      // than thrown over, and named in the result so the caller can say so.
      const data = {}, dropped = [];
      for (const { path: rp, value } of reads) {
        try { JSON.parse(JSON.stringify(value)); data[rp] = value; }
        catch (e) { dropped.push(rp); }
      }

      const { text } = await gh.get(path);
      const baked = await bakeHtml(gh, text, { scripts: opts.scripts, data });
      return {
        html: baked.html, path, base: path.split('/').pop(),
        codeFiles: baked.codeFiles, chainless: !!baked.chainless,
        reads: Object.keys(data), dropped, bytes: baked.html.length,
        cdnRefs: cdnRefs(baked.html),
      };
    },

    // Build and download. Same opts as build(); returns the manifest sans files.
    async page(opts = {}) {
      await ensureIo();
      const b = await exporter.build(opts);
      await window.io.saveZip(b.files, b.filename);
      return { path: b.path, base: b.base, filename: b.filename, offline: b.offline, codeFiles: b.codeFiles, reads: b.reads };
    }
  };

  window.exporter = exporter;
})();
