// export.js — export a page to a portable, self-resolving copy: "download this
// page plus the data it read()s" as one zip, optionally with its code inlined.
//
// read() resolves a path local-first: a <script src=path> sitting beside the
// page (page-relative) wins over the repo copy (root-relative). This kit emits
// the page laid out so that wins with zero manual placement:
//
//   <page-basename>.html      ← page source (baked, if offline), at the zip root
//   <read-path>               ← each read() value, frozen to the local form
//
// Because the HTML is at the zip root, page-relative and bundle-relative
// coincide: a read path like 'data/sample.js' lands at 'data/sample.js' beside
// the HTML, and read('data/sample.js') resolves it local on file://.
//
// Which data? The data the page read()s. gh-boot.js wraps read() to record each
// resolved read on window.__reads, so a page "declares" its data simply by
// reading it. Callers can also pass reads explicitly (opts.reads) — handy when a
// page already holds the value (the cross-repo-read demo does) or wants to export
// data it hasn't read through read() itself.
//
// Two modes (the FAB toggles them):
//   default        — local-DATA: data is frozen local, but the page still boots
//                    its CODE from the CDN. Smaller; needs network for code.
//   { offline:true } — also bakes the gh.load chain in (via kits/build.js), so
//                    unzip-and-open works with no network at all. Third-party libs
//                    (Tailwind/Alpine/Phosphor) still come from the CDN.
//
// This is the "export" leg of the vocabulary: load → build → bake → export.
(() => {
  // Freeze a read() value into the local deposit form: the file read()'s local
  // probe injects as <script>, which sets document.currentScript.value.
  const localForm = (path, value) =>
    `// ${path} — local form (generated by the export kit). Place beside the\n` +
    `// page so read('${path}') resolves this before the repo copy.\n` +
    `document.currentScript.value = ${JSON.stringify(value, null, 2)};\n`;

  // The page's own repo path. The FAB stamps it on its host element
  // (data-path="pages/foo.html"); fall back to nothing so callers pass opts.path.
  const ownPath = () => document.querySelector('[data-path]')?.dataset.path || '';

  const ensureIo = async () => {
    if (window.io?.saveZip) return;
    if (window.gh?.load) { try { await window.gh.load('kits/io.js'); } catch (e) {} }
    if (!window.io?.saveZip) throw new Error('io.saveZip unavailable (kits/io.js failed to load)');
  };

  const ensureBuildKit = async () => {
    if (window.buildKit) return;
    if (window.gh?.load) { try { await window.gh.load('kits/build.js'); } catch (e) {} }
    if (!window.buildKit) throw new Error('buildKit unavailable (kits/build.js failed to load)');
  };

  // Bake the page's code into the HTML: collect the gh.load chain at runtime,
  // emit the build, and rewrite the gh-api.js import to carry it inline. The
  // result boots with no network (the data files below cover read() the same way).
  const bakeHtml = async (gh, html) => {
    await ensureBuildKit();
    const { ghApiSrc, cache } = await window.buildKit.collectCache(gh);
    const buildJs = window.buildKit.emit({
      ghApiSrc, cache,
      repo: gh.repo || 'mehrlander/web-tools',
      defaultRef: gh.ref || window.__bundleRef || 'main',
    });
    return { html: window.buildKit.bake(html, buildJs), codeFiles: Object.keys(cache).length };
  };

  const exporter = {
    localForm,

    // Assemble the file list without downloading — for previews/UI. With
    // opts.offline, the HTML is baked so the zip opens with no network at all
    // (code inlined + data local). Returns
    // { path, base, filename, offline, codeFiles, reads:[paths], files:[{path,data}] }.
    async build(opts = {}) {
      const gh = window.gh;
      if (!gh?.get) throw new Error('window.gh required (gh.get fetches the pristine page source)');

      const path = opts.path || ownPath();
      if (!path) throw new Error('No page path: pass opts.path or set a [data-path] element (the FAB carries it)');

      // Default to the recorded reads; map to the {path,value} shape build needs.
      const reads = opts.reads
        || (window.__reads ? window.__reads.map(r => ({ path: r.path, value: r.value })) : []);

      // Pristine repo copy at the booted ref — not document.documentElement
      // .outerHTML, which is the mutated post-Alpine DOM. On a ?use=<sha> page
      // gh.ref is that sha, so the export captures exactly the version running.
      const { text } = await gh.get(path);
      const base = path.split('/').pop();

      let html = text, codeFiles = 0;
      if (opts.offline) ({ html, codeFiles } = await bakeHtml(gh, text));

      const files = [{ path: base, data: html }];
      for (const { path: p, value } of reads) files.push({ path: p, data: localForm(p, value) });

      const suffix = opts.offline ? '-offline.zip' : '-export.zip';
      const filename = opts.filename || base.replace(/\.html?$/i, '') + suffix;
      return { path, base, filename, offline: !!opts.offline, codeFiles, reads: reads.map(r => r.path), files };
    },

    // Build and download. Same opts as build(); returns the manifest sans files.
    async page(opts = {}) {
      await ensureIo();
      const b = await exporter.build(opts);
      await window.io.saveZip(b.files, b.filename);
      return { path: b.path, base: b.base, filename: b.filename, offline: b.offline, codeFiles: b.codeFiles, reads: b.reads };
    }
  };

  window.exporter = exporter;
})();
