// kits/guide-render.js — a guide PR body, rendered as something you can walk.
//
// A guide body is markdown written for GitHub: every file it names is a blob
// link, which is the right answer for a reader standing on github.com and the
// wrong one for a reader standing in the thing the guide describes. There the
// link should reach the RENDERER that can show the file, not its source.
//
// So this kit does two jobs over one parse:
//
//   RE-AIM     every recognised blob link is pointed at the renderer for its
//              kind (a page at the toss, a data-ish file at the data view) and
//              stamped with its address, so a host can intercept the tap and
//              render in place instead of navigating.
//   COLLECT    the same links, deduped BY FILE, become a chip strip: the
//              guide's file list as a menu rather than as prose to re-read.
//
// Parsing the rendered HTML rather than string-replacing the markdown keeps one
// definition of what a link is (the parser's), so a link written inline, as a
// reference, or as an autolink all get the same treatment.
//
// Extracted from alpineComponents/fab.js on 2026-08-06, where it had been the
// drawer's alone. It moved because the FAB is not the only surface that shows a
// guide: pages/branch.html renders the same body under the same rules, and the
// estate's branch takeover renders that page full-viewport. One renderer, three
// places it appears.
//
// Pure but for `render`, which needs a DOM parser (the browser's, or jsdom's in
// a test). No fetch, no Alpine, no `this`. Attaches to window.GuideRender.
(() => {
  const BASE = 'https://mehrlander.github.io/web-tools/pages/toss-render.html';
  // THE TOSS'S MARK, and it is the chat convention's own glyph rather than a
  // second one. SURFACING.md writes a render link as 🥏 and has since the
  // primitive was named; the app drew ph-disc, so one mechanism had two marks
  // and a reader crossing from a reply to the row had to learn both. The
  // frisbee is the noun everything here already uses for the thing ("toss a
  // live view"), which a disc only resembles.
  //
  // It rides on the TARGET rather than being typed into each template, for the
  // reason every other field here does: three strips render these chips and a
  // character repeated in three files is three places to disagree.
  const MARK = '🥏';
  const DATA_EXT = ['md', 'markdown', 'csv', 'tsv', 'json', 'txt', 'log', 'yml', 'yaml'];

  // How a rendered body is styled: one injected stylesheet, not utility classes.
  //
  // It was utility classes, in the arbitrary-variant form (`[&_a]:text-primary`,
  // `[&_ul]:list-disc`), and half of them silently produced nothing. daisyUI
  // ships its color utilities PREBUILT in its own stylesheet, so a bare
  // `text-primary` works while `[&_a]:text-primary` has to be generated by the
  // Tailwind browser build, which has no knowledge of daisyUI's theme tokens
  // and emits no rule at all. Core utilities in the same string (`underline`,
  // `list-disc`) generated fine, so a guide rendered with bullets and
  // underlines and never once with a blue link, in the FAB since PR #295 and
  // here since the day this kit was extracted, with nothing in any console.
  //
  // Real CSS removes the whole class of failure: no generation step, no
  // dependency on when a class reaches the DOM relative to a scan, and the
  // daisyUI variables are read at paint time so a theme swap still follows.
  // The two sizes are one base class plus a modifier, since only the type scale
  // and the spacing differ between a full-width page and the FAB's drawer.
  const STYLE_ID = 'guide-render-style';
  const CSS = `
.guide-body{font-size:.875rem;line-height:1.625;overflow-wrap:break-word}
.guide-body>*:first-child{margin-top:0}
.guide-body>*:last-child{margin-bottom:0}
.guide-body p,.guide-body ul,.guide-body ol{margin:.5rem 0}
.guide-body ul{padding-left:1.25rem;list-style:disc}
.guide-body ol{padding-left:1.25rem;list-style:decimal}
.guide-body li{margin:.125rem 0}
.guide-body li::marker{color:color-mix(in oklab,currentColor 40%,transparent)}
.guide-body a{color:var(--color-primary);text-decoration:underline;text-underline-offset:2px;
  text-decoration-color:color-mix(in oklab,var(--color-primary) 40%,transparent)}
.guide-body strong{font-weight:600}
.guide-body em{font-style:italic}
.guide-body h1,.guide-body h2,.guide-body h3{font-weight:600;margin:.75rem 0 .25rem}
.guide-body h1{font-size:1rem}
.guide-body h2,.guide-body h3{font-size:.875rem}
.guide-body code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.75rem;
  background:color-mix(in oklab,var(--color-base-300) 50%,transparent);padding:0 .25rem;border-radius:.25rem}
.guide-body pre{background:color-mix(in oklab,var(--color-base-300) 40%,transparent);
  padding:.5rem;border-radius:.25rem;overflow-x:auto;font-size:.75rem;margin:.5rem 0}
.guide-body pre code{background:transparent;padding:0}
.guide-body blockquote{border-left:2px solid var(--color-base-300);padding-left:.5rem;opacity:.8}
/* A wide table scrolls rather than widening the body. display:block is the
   one-rule way to do it and it costs something: the table no longer fills the
   width, so a narrow one hugs its content instead of stretching. Where
   kits/md-doc.js has been over this markup it has already put the table in a
   scroller of its own, which keeps width:100% and so keeps a narrow table
   stretched, so that case opts back out. One owner per table, decided by which
   one got there.
   DEFAULT PLUS EXCEPTION, not a :not() on the parent. The parent form was
   ".guide-body :not([data-md-scroll])>table", which needs an element BETWEEN
   the body and the table, so a table at the top level of a document was the
   one shape it never matched, which is most of them. Measured 2026-09-06 at
   390px: a SNAGS.md table 398px wide in a 358px pane, the pane scrolling
   sideways, and that scroll eating the horizontal gesture meant for the strip
   the pane now sits in.
   (No backticks in here: this block lives inside a template literal.) */
.guide-body table{display:block;overflow-x:auto;font-size:.75rem;border-collapse:collapse}
.guide-body [data-md-scroll]>table{display:table;overflow-x:visible}
/* Cells were never ruled. border-collapse:collapse above is the tell: it was
   set for borders that no rule ever drew, so every table in every guide body
   rendered as loose columns of text with nothing separating a header from its
   rows. Reported 2026-09-16 on a skill file's two-row table, which read as one
   run-on line. Hairlines rather than a grid: a table in prose wants to be
   readable, not boxed. */
.guide-body th,.guide-body td{padding:.25rem .5rem;text-align:left;vertical-align:top;
  border-bottom:1px solid color-mix(in oklab,var(--color-base-300) 70%,transparent)}
.guide-body thead th{font-weight:600;border-bottom-width:2px}
.guide-body tbody tr:last-child td{border-bottom:0}
/* Fenced code: the language, and the colours. kits/md-doc.js hangs the label
   and runs Prism; the palette lives here because it has to answer to the THEME.
   Prism's own stylesheet paints a fixed light background and fixed token
   colours, which is why it is deliberately not loaded: these are daisyUI's
   variables, so a highlighted block reads the same way in every theme and
   stays legible in a dark one. Five roles is the whole set worth having in
   prose; anything finer is an editor's job, not a document's. */
.guide-body pre .md-fence-lang{position:absolute;top:.25rem;right:.5rem;
  font-size:.625rem;line-height:1;letter-spacing:.02em;text-transform:lowercase;
  opacity:.5;user-select:none;pointer-events:none}
.guide-body pre .token.comment,.guide-body pre .token.prolog,
.guide-body pre .token.doctype,.guide-body pre .token.cdata{opacity:.6;font-style:italic}
.guide-body pre .token.string,.guide-body pre .token.attr-value,
.guide-body pre .token.char,.guide-body pre .token.regex{color:var(--color-success)}
.guide-body pre .token.keyword,.guide-body pre .token.selector,
.guide-body pre .token.important,.guide-body pre .token.atrule{color:var(--color-secondary)}
.guide-body pre .token.number,.guide-body pre .token.boolean,
.guide-body pre .token.constant,.guide-body pre .token.symbol{color:var(--color-accent)}
.guide-body pre .token.function,.guide-body pre .token.class-name,
.guide-body pre .token.tag,.guide-body pre .token.property{color:var(--color-primary)}
.guide-body pre .token.punctuation,.guide-body pre .token.operator{opacity:.7}
/* The roles above were written for general-purpose code and reached none of
   MARKDOWN's token names, which is the one language a documentation surface is
   guaranteed to quote: a fence of markdown highlighted into tokens Prism
   emitted and this palette had no colour for, so it rendered as plain text
   twice over. Measured 2026-09-17 by counting tokens per fence: the markdown
   blocks carried bold, blockquote, content and punctuation, and only the last
   was coloured. Grouped by ROLE rather than by language, so the next grammar
   lands in a role that already exists. */
.guide-body pre .token.title,.guide-body pre .token.selector .token.class,
.guide-body pre .token.namespace{color:var(--color-primary);font-weight:600}
.guide-body pre .token.bold{font-weight:700}
.guide-body pre .token.italic{font-style:italic}
.guide-body pre .token.strike{text-decoration:line-through;opacity:.7}
.guide-body pre .token.list,.guide-body pre .token.hr,
.guide-body pre .token.blockquote{color:var(--color-secondary)}
.guide-body pre .token.url,.guide-body pre .token.url-reference{color:var(--color-accent)}
.guide-body pre .token.code-snippet,.guide-body pre .token.code{color:var(--color-success)}
.guide-body pre .token.variable,.guide-body pre .token.parameter{color:var(--color-accent)}
.guide-body pre .token.function-name,.guide-body pre .token.builtin{color:var(--color-primary)}
.guide-body th{text-align:left;padding-right:.75rem}
.guide-body td{padding-right:.75rem}
.guide-body hr{margin:.5rem 0;border-color:var(--color-base-300)}
.guide-body img{max-width:100%}
/* A file path found in prose (stylePaths) reads as code but at the prose's own
   scale: the fixed code size would make the most-scanned tokens the smallest
   text on the screen. */
.guide-body code.guide-path{font-size:.9em}
.guide-body-sm{font-size:.8125rem}
.guide-body-sm p,.guide-body-sm ul,.guide-body-sm ol{margin:.375rem 0}
.guide-body-sm ul,.guide-body-sm ol{padding-left:1rem}
.guide-body-sm code,.guide-body-sm pre,.guide-body-sm table{font-size:.6875rem}
.guide-body-sm h1,.guide-body-sm h2,.guide-body-sm h3{font-size:.8125rem}
/* A phone reads the guide at body size, not caption size: the 14px scale that
   suits a desktop card beside other panes is the whole screen in the branch
   takeover, and it read small (measured twice; 1rem still read small in the
   takeover, so the scale sits above the platform default). The drawer modifier
   stays put, since the FAB drawer is a desktop surface. */
@media (max-width:640px){
  .guide-body:not(.guide-body-sm){font-size:1.0625rem;line-height:1.6}
  .guide-body:not(.guide-body-sm) code,.guide-body:not(.guide-body-sm) pre,
  .guide-body:not(.guide-body-sm) table{font-size:.9375rem}
  .guide-body:not(.guide-body-sm) h1{font-size:1.25rem}
  .guide-body:not(.guide-body-sm) h2,.guide-body:not(.guide-body-sm) h3{font-size:1.0625rem}
}
`;
  function ensureStyle() {
    if (typeof document === 'undefined' || document.getElementById(STYLE_ID)) return;
    const el = document.createElement('style');
    el.id = STYLE_ID;
    el.textContent = CSS;
    document.head.appendChild(el);
  }

  // `drawer` is the FAB's right-side panel, `page` a full-width page. Injects on
  // first ask, so a host that never renders a guide pays nothing.
  function bodyClass(size) {
    ensureStyle();
    return size === 'drawer' ? 'guide-body guide-body-sm' : 'guide-body';
  }

  // A blob URL's `<ref>/<path>` tail cannot be split by counting slashes,
  // because a ref may contain them and in this estate always does: every
  // session branch is `claude/<slug>`, so the naive first-segment split yields
  // ref `claude` and a path starting with the rest of the branch name. Both
  // halves are then wrong and the resulting address 404s.
  //
  // The known refs are the disambiguator: match the LONGEST one that prefixes
  // the tail. Falls back to the first segment, which is right for a sha, a tag,
  // and any unslashed branch, and is the best available guess before a caller
  // has a branch list to offer.
  function splitBlobRef(rest, knownRefs) {
    if (!rest || !rest.includes('/')) return null;
    const known = (knownRefs || []).filter(Boolean).slice()
      .sort((a, b) => b.length - a.length);
    for (const ref of known) {
      if (rest.startsWith(ref + '/')) return { ref, path: rest.slice(ref.length + 1) };
    }
    const i = rest.indexOf('/');
    return { ref: rest.slice(0, i), path: rest.slice(i + 1) };
  }

  // Where a repo file opens. The one routing table, read by a guide's links and
  // by the FAB's path picker, differing only in `any`:
  //
  //   .html            the toss, the renderer for a page
  //   data-ish files   the data view (markdown renders as preview there)
  //   anything else    null, unless `any` — a picker may be less careful than a
  //                    link, because a picker's user asked for that exact file
  function renderTarget(repo, ref, path, any) {
    if (!repo || !path) return null;
    // No ref is not a missing ref: the grammar reads a bare repo:path as the
    // repo's default branch, which is exactly what a cross-repo pick means.
    // Only the title has to say so, since "at " with nothing after it would
    // read as a bug.
    const addr = repo + (ref ? '@' + ref : '') + ':' + path;
    const at = ref ? ' at ' + ref : ' at its default branch';
    const ext = (path.split('.').pop() || '').toLowerCase();
    const label = path.split('/').pop();
    // `addr` rides alongside the url because an in-place re-address needs the
    // address, not the link: a renderer already open would otherwise reload its
    // shell to reach a state it can reach where it stands.
    if (ext === 'html' || ext === 'htm') {
      return { kind: 'render', repo, ref, path, addr, url: BASE + '#gh=' + addr,
               label, icon: 'ph-disc', mark: MARK, title: 'Render ' + path + at };
    }
    if (any || DATA_EXT.includes(ext)) {
      return { kind: 'read', route: 'data', repo, ref, path, addr, url: BASE + '#data=' + addr,
               label, icon: 'ph-file-text', title: 'Read ' + path + at };
    }
    return null;
  }

  // ── The pages a CHANGE SET can be looked at through ──────────────────────
  //
  // renderTarget answers for one file in isolation. This answers for a set of
  // changed paths, and it carries the one rule renderTarget cannot: in a repo
  // whose pages are framed by an app, a changed page is not addressable on its
  // own. The app is what mounts it, so a toss straight at the page renders a
  // document that boots into nothing, which docs/showing-mechanisms.csv records
  // as the route the session store got wrong most often.
  //
  // `showing` is that repo's .web-tools.json `showing` block, the same three
  // fields scripts/showing.py reads, so the app and this estate's own script
  // pick the same mechanism from the same declaration rather than from two
  // codified opinions:
  //
  //   app      the page that frames the others
  //   app_dir  the app's own folder; a changed page in it IS the app
  //   views    { <view key>: <path prefix it frames> }
  //
  // Paths under one view collapse to ONE chip, because they are one thing to
  // open: the app on that view. A repo with no `showing` block, or a path
  // outside every declared prefix, falls through to renderTarget unchanged,
  // which is what makes this safe to call for every repo.
  const stem = (p) => String(p).split('/').pop().replace(/\.html?$/i, '');

  function pageTargets(repo, ref, paths, showing) {
    const app = (showing && showing.app) || '';
    const appDir = (showing && showing.app_dir) || '';
    const views = (showing && showing.views) || {};
    const at = ref ? ' at ' + ref : ' at its default branch';
    const out = [], seen = new Set();
    for (const raw of paths || []) {
      const path = String(raw || '');
      if (!/\.html?$/i.test(path)) continue;
      let target = null;
      if (app) {
        // The LONGEST matching prefix wins, so a view nested inside another
        // one's folder resolves to itself rather than to its parent.
        let key = '', prefix = '';
        for (const [k, p] of Object.entries(views)) {
          if (p && path.startsWith(p) && p.length > prefix.length) { key = k; prefix = p; }
        }
        if (key) {
          const addr = repo + (ref ? '@' + ref : '') + ':' + app + '?view=' + key;
          target = { kind: 'render', framed: true, repo, ref, path: app, view: key, addr,
                     url: BASE + '#gh=' + addr, label: key, short: key,
                     icon: 'ph-disc', mark: MARK,
                     title: 'Open ' + key + ' in ' + app + at
                            + ' (' + path.split('/').pop() + ' is framed by the app, not addressable alone)' };
        } else if (path === app || (appDir && path.startsWith(appDir))) {
          const addr = repo + (ref ? '@' + ref : '') + ':' + app;
          target = { kind: 'render', framed: true, repo, ref, path: app, view: '', addr,
                     url: BASE + '#gh=' + addr, label: app.split('/').pop(),
                     short: stem(app), icon: 'ph-disc', mark: MARK,
                     title: 'Render ' + app + at };
        }
      }
      if (!target) {
        target = renderTarget(repo, ref, path);
        // `short` is a SECOND label, not a replacement: a strip inside a list
        // row has about 220px and a mono filename runs 120 to 170 of it, so two
        // chips never share a line while a detail's full-width row fits four.
        // The extension is what goes, since the disc already says "a page" and
        // the title carries the path whole.
        if (target) target = { ...target, short: stem(path) };
      }
      if (!target || target.kind !== 'render') continue;
      if (seen.has(target.url)) continue;
      seen.add(target.url);
      out.push(target);
    }
    return out;
  }

  // A file path in PROSE, styled as one. The caption convention writes
  // filenames plain ("Filenames stay plain and link words are tappable"), so
  // a rendered guide showed its most-scanned tokens in body type. This pass
  // wraps path-shaped tokens in <code class="guide-path"> after the parse:
  // renderer-side on purpose, so bodies stay plain markdown for GitHub and
  // every surface that renders through this kit (the FAB drawer, the branch
  // page, the takeover) styles them the same. The extension whitelist is what
  // keeps "e.g." and version numbers out; anchors, code, and pre are skipped,
  // a link's label being already styled by being a link.
  const PATH_RE = /(?:[\w.-]+\/)*[\w-][\w.-]*\.(?:mjs|cjs|jsx?|tsx?|json|html?|css|md|markdown|csv|tsv|py|sh|bash|yml|yaml|toml|txt|log|svg|png|jpe?g|gif|pdf|xlsx?)\b/g;
  function stylePaths(doc) {
    const skip = new Set(['A', 'CODE', 'PRE']);
    (function walk(node) {
      for (const child of [...node.childNodes]) {
        if (child.nodeType === 1) { if (!skip.has(child.tagName)) walk(child); continue; }
        if (child.nodeType !== 3) continue;
        const text = child.nodeValue;
        PATH_RE.lastIndex = 0;
        if (!PATH_RE.test(text)) continue;
        const frag = doc.createDocumentFragment();
        let last = 0;
        PATH_RE.lastIndex = 0;
        for (let m; (m = PATH_RE.exec(text)); ) {
          if (m.index > last) frag.appendChild(doc.createTextNode(text.slice(last, m.index)));
          const c = doc.createElement('code');
          c.className = 'guide-path';
          c.textContent = m[0];
          frag.appendChild(c);
          last = m.index + m[0].length;
        }
        if (last < text.length) frag.appendChild(doc.createTextNode(text.slice(last)));
        child.replaceWith(frag);
      }
    })(doc.body);
  }

  // Returns null for a link that should pass through untouched, so callers can
  // treat "no opinion" and "re-aim here" as the same branch.
  function openTarget(href, knownRefs) {
    const m = /^https?:\/\/github\.com\/([^/]+)\/([^/]+)\/blob\/(.+?)(?:[?#].*)?$/i.exec(href || '');
    if (!m) return null;
    const [, owner, name, rest] = m;
    let tail = rest;
    try { tail = decodeURIComponent(rest); } catch {}
    const split = splitBlobRef(tail, knownRefs);
    if (!split) return null;
    return renderTarget(owner + '/' + name, split.ref, split.path);
  }

  // markdown -> { html, targets, byAddr }.
  //
  // `resolve(href)` decides where a link goes; the default reads blob URLs
  // against `knownRefs`. `preferRef` breaks a dedupe tie, which is not a detail:
  // a guide names each changed file three times by convention, [new] and [main]
  // and [diff], and the first two are the same file at two refs. Deduping on
  // the ADDRESS gave a strip listing index.html twice, which reads as a bug
  // and is useless as a menu. Keyed by kind and path, the ref the reader is
  // looking at wins. The PROSE keeps every link re-aimed individually, since
  // there both refs are meaningful: the sentence around them says which is
  // which.
  function render(markdown, opts) {
    const o = opts || {};
    const marked = o.marked || (typeof window !== 'undefined' && window.marked);
    const parser = o.DOMParser || (typeof DOMParser !== 'undefined' && DOMParser);
    const empty = { html: '', targets: [], byAddr: {} };
    if (!markdown || !marked || !parser) return empty;
    let html = '';
    try { html = marked.parse(markdown); } catch { return empty; }
    const resolve = o.resolve || (href => openTarget(href, o.knownRefs));
    const doc = new parser().parseFromString(html, 'text/html');
    const byFile = new Map(), targets = [], byAddr = {};
    for (const a of doc.querySelectorAll('a[href]')) {
      const t = resolve(a.getAttribute('href'));
      if (!t) {
        // Not something a host can render: a session link, a compare view, an
        // issue. Those still belong to GitHub and still open away.
        a.setAttribute('target', '_blank');
        a.setAttribute('rel', 'noopener');
        continue;
      }
      // A renderable link keeps its href so a long-press can still copy a
      // durable address; a host that wants in-place rendering intercepts the
      // ordinary tap on data-render-addr.
      a.setAttribute('href', t.url);
      a.setAttribute('title', t.title);
      a.setAttribute('data-render-addr', t.addr);
      byAddr[t.addr] = t;
      const key = t.kind + '|' + t.path;
      const held = byFile.get(key);
      if (!held) { byFile.set(key, t); targets.push(t); continue; }
      if (o.preferRef && held.ref !== o.preferRef && t.ref === o.preferRef) {
        targets[targets.indexOf(held)] = t;
        byFile.set(key, t);
      }
    }
    stylePaths(doc);
    return { html: doc.body.innerHTML, targets, byAddr };
  }

  // marked, lazily and once per page. Same URL and same shape source-peek.js
  // and chat-render.js use, so the three share one cached asset.
  let markedP = null;
  function needMarked() {
    return markedP ||= window.marked ? Promise.resolve() : new Promise((res, rej) => {
      const s = document.createElement('script');
      s.src = 'https://cdn.jsdelivr.net/npm/marked/lib/marked.umd.js';
      s.onload = res; s.onerror = () => rej(new Error('marked failed to load'));
      document.head.appendChild(s);
    });
  }

  window.GuideRender = { BASE, MARK, CSS, bodyClass, ensureStyle, splitBlobRef, renderTarget, pageTargets, openTarget, render, needMarked };
})();
