// land.js — where the reader was just sent, and how they get told.
//
// One question, asked after every address the estate resolves: DID THIS LAND
// WHERE I MEANT. A surface that scrolls to a place and says nothing answers it
// only by accident, since a mark that is simply present cannot be told from one
// that was already there, and a reader who followed a link and saw no motion
// cannot tell a hit from a miss.
//
// LIFTED FROM A SECOND IMPLEMENTATION RATHER THAN INVENTED. mehrlander/home's
// budget-drs submittal view has answered this for months, over two very
// different subjects: a block of prose in an office document, and a rectangle
// on a page of a PDF. Its `landOn`, `scrollerOf` and `.landed` live inline in
// projects/budget-drs/submittal/submittal.html, and the Map view's Surfacing
// tab arrived at a near-identical scroller walk independently on 2026-09-04,
// which is the second implementation that makes this a kit. The numbers below
// are that page's, measured there; the smooth scroll and the reduced-motion
// gate are new to this copy. home is the second consumer, not the source of
// truth: when it adopts this, its inline copy goes.
//
//   Land.mark(el, opts?)   scroll to `el`, tint it, fade the tint
//   Land.clear(root)       drop every mark under `root`
//   Land.scrollerOf(el)    the nearest ancestor that actually scrolls
//
// NOT A HIGHLIGHTER, and the distinction decides the timing. A highlighter is
// persistent and means "this matters"; a landing is transient and means "here",
// which is a thing worth saying once. So it fades, and after that the reader is
// looking at the document rather than at the app's answer about the document.
//
// THE PDF CASE IS ALREADY BUILT, which the first draft of this file got wrong.
// kits/pdf.js has carried a full find-and-land for months: `find(hits)` draws
// a rectangle per hit off the text layer, `findGo(k)` moves between them, and
// `repaint(i)` exists so a changed overlay reaches a page already on screen.
// So the estate had EIGHT landings in seven files across two repos, disagreeing
// about where a landing sits (centre, 0.28, a fixed 80px above a drawn region)
// and what colour it is (warning at three strengths, an off-palette orange, and
// primary). A first count said six and missed two, because both were reached by
// grepping for the scroll and both do more than scroll. Three of pdf.js's
// lessons are folded in below.
//
// TWO OF THE EIGHT STAY WHERE THEY ARE, and saying which sharpens what this is:
//   fab.js's `highlight` has no dwell and a "clear" button beside it. That is a
//   HIGHLIGHTER, persistent and meaning "this matters", which the line above
//   says this kit is not. Converting it would have taken the reader's control
//   of it away.
//   annotate.js lands on a foreign page the reader is annotating, and its 80px
//   is a gap above a rectangle they drew rather than a fraction of a pane. A
//   fraction is the wrong shape for a target with no container.
// state-view.js's `aim` did convert, for the scroll only: its tint is Alpine's,
// driven reactively off the selected item, and a kit adding a class beside that
// would paint the sum of two owners.
//
// Only the tints and LAND_AT are shared with it, and by COPY held to a gate
// (tools/test/land-parity.test.mjs) rather than by a call: pdf.js has no kit
// dependencies, is loaded straight from jsDelivr on one path, and runs on
// pages/pdf-inspect.html which loads nothing else. A copy that cannot be
// eliminated is held two-way by test, which is the same bargain
// deck-entry-parity makes for the deck door.
//
// Attaches to window.Land. No CSS of its own: the tint and the fade are
// Tailwind utilities, generated by the browser build the same way a class in a
// component template is, so the page's theme owns the colour.

(() => {
  // WHERE A LANDING SITS, and it is one number for every surface. Centred is
  // wrong twice, and both were measured in home rather than argued: for a SET,
  // the first of seven lit rows in the middle of the pane pushes its siblings
  // off the bottom; for a DOCUMENT, half a screen of the previous section sits
  // above the heading you asked for, which reads as having landed early.
  //
  // A little over a quarter down leaves what was found near the top with its
  // context still visible, which is where a reader expects to have arrived.
  const LAND_AT = 0.28;

  // Long enough to find with the eye after the scroll settles, short enough
  // that it is gone before it becomes furniture.
  const DWELL = 4000;

  // The tint, as utilities rather than a stylesheet. `bg-warning/30` compiles to
  // color-mix(in oklab, var(--color-warning) 30%, transparent), which is
  // character for character what home's `.landed` declares, so the two surfaces
  // are the same yellow by construction rather than by a matched hex.
  //
  // TWO STRENGTHS, because a landing on a SET has a current member. That is
  // pdf.js's second lesson: its find draws the active hit strong with a ring
  // and the rest weak, so a reader stepping through seven hits can see both
  // where they are and how many there are. home's landOn lights every member
  // of a set identically and can only say "these seven", never "this one of
  // seven".
  //
  // /10 rather than the /15 this was written with: Tailwind's opacity scale has
  // no 15 step, so the class compiled to nothing and the weaker mark would have
  // been invisible. tools/test/dead-opacity.test.mjs is what said so, which is
  // the reason a tint in the FLOW is a class and a tint over a PAGE is a
  // color-mix string: the class is checkable and the string is free.
  const MARK = ['bg-warning/30'];
  const MARK_REST = ['bg-warning/10'];
  // Left on the element after the tint comes off, because the removal is what
  // the transition is FOR: taking these off at the same time would cut the fade
  // and the mark would vanish rather than recede. A colour transition left on a
  // node costs nothing until something changes its colour again.
  const FADE = ['transition-colors', 'duration-1000', 'ease-out'];

  const timers = new WeakMap();

  const reduced = () => {
    try { return matchMedia('(prefers-reduced-motion: reduce)').matches; }
    catch { return false; }
  };

  // The nearest ancestor that actually scrolls vertically. Walked rather than
  // named because one landing serves panes the caller does not enumerate: a
  // list column, a document reader's own column, a deck slide. The `+ 4` is
  // slop against sub-pixel layout reporting a scrollable box that is not.
  function scrollerOf(el) {
    for (let p = el?.parentElement; p; p = p.parentElement) {
      const oy = getComputedStyle(p).overflowY;
      if ((oy === 'auto' || oy === 'scroll') && p.scrollHeight > p.clientHeight + 4) return p;
    }
    return null;
  }

  // Every mark under `root`, off. The caller owns WHEN: a search that lights a
  // set clears before it searches, so a miss leaves nothing lit, while an
  // address naming one row by id has nothing to clear.
  function clear(root) {
    const sel = [...MARK, ...MARK_REST].map(c => '.' + c.replace('/', '\\/')).join(',');
    for (const el of (root || document).querySelectorAll(sel)) {
      clearTimeout(timers.get(el));
      el.classList.remove(...MARK, ...MARK_REST);
    }
  }

  // Land on `el`. Options:
  //   scroll    false to light it without moving, for every member of a set
  //             after the first: a count that lands on seven rows should move
  //             the reader once and light all seven, not walk down the list.
  //   ifNeeded  scroll only when `el` is not already fully in view, so a tap on
  //             something the reader can see does not jump under the finger.
  //   dwell     ms before the tint starts to go.
  //   smooth    false to jump; ignored (and forced off) under reduced motion.
  //   current   false for a member of a set that is not the one being read,
  //             drawn weaker so the set and the place inside it are two
  //             different things a reader can see at once.
  //   tint      false to move without marking, for the element the reader is
  //             ALREADY on: a list row whose detail just opened has to be kept
  //             in view when the layout reflows under it, and lighting it would
  //             answer a question nobody asked. The pair is one landing with
  //             two ends, and only the far end is news.
  //   settle    false to scroll exactly once. By default the scroll is
  //             re-asserted twice, on the next frame and again at 400ms, and
  //             only if the target has MOVED: see the note by `again`.
  //
  // ONLY THE SCROLLER MOVES. scrollIntoView walks every scrollable ancestor,
  // and a surface that keeps a list beside a document is a surface where that
  // is wrong: centring a paragraph in the reader scrolled the list it was
  // opened from off the screen. The fallback for an element in no scroller is
  // scrollIntoView, since there the page IS the scroller.
  function mark(el, o = {}) {
    if (!el) return false;
    const smooth = o.smooth !== false && !reduced();
    // 'instant', NOT 'auto', and the difference is the whole reduced-motion
    // gate. 'auto' does not mean "no animation": it means "use the element's
    // computed scroll-behavior", so on any scroller carrying Tailwind's
    // `scroll-smooth` this would animate the scroll of the reader who asked
    // that it not. kits/pdf.js states the same trap from the other end, which
    // is where this was found: it refuses `scroll-smooth` on its flow because
    // the CSS property reaches a plain `scrollTop =` too, and its opening seek
    // must land instantly.
    const behavior = smooth ? 'smooth' : 'instant';
    if (o.scroll !== false) {
      const box = scrollerOf(el);
      const r = el.getBoundingClientRect();
      if (!box) {
        // Guarded rather than called, the rule branch-brief.js already settled:
        // jsdom implements no scrolling at all, and a landing is reached from
        // enough places that a throw inside one would break its caller's flow
        // rather than merely failing to scroll.
        if (typeof el.scrollIntoView === 'function') {
          try { el.scrollIntoView({ block: 'start', behavior }); } catch { /* no scrolling here */ }
        }
      } else {
        const b = box.getBoundingClientRect();
        const seen = r.top >= b.top && r.bottom <= b.bottom;
        if (!(o.ifNeeded && seen)) {
          // Where `el` sits in the scroller's CONTENT, which a scroll in flight
          // does not change: the rect moves and scrollTop moves by the same
          // amount. So two readings that differ mean the layout moved, never
          // that the scroll is still travelling.
          const target = () => {
            const bb = box.getBoundingClientRect();
            return box.scrollTop + (el.getBoundingClientRect().top - bb.top) - bb.height * LAND_AT;
          };
          let asked = target();
          box.scrollTo({ top: asked, behavior });
          // SCROLLED AGAIN, and the second time is not belt and braces. A
          // scroll is taken against the scroller's size at that instant, and
          // the pane a landing runs in is often still settling: a docked pane
          // is laid out by its split, a deck slide sizes to a host that has
          // just been filled, a document column corrects its page heights in
          // a pass it does not await. Measured in mehrlander/home on
          // 2026-08-29 from a search result on a phone: the element was found
          // and marked, and the pane still showed the document's first line,
          // because the scroller had grown under a scroll already taken.
          // Re-asserting once the layout has settled is cheaper than
          // detecting the settle, which has no event: nothing is recomputed
          // unless the target moved, so a pane that was stable costs two
          // comparisons and no motion, and a smooth scroll in flight is not
          // restarted toward the place it is already going.
          if (o.settle !== false) {
            const again = () => {
              if (!el.isConnected || !box.isConnected) return;
              const t = target();
              if (Math.abs(t - asked) > 1) { asked = t; box.scrollTo({ top: t, behavior }); }
            };
            requestAnimationFrame(again);
            setTimeout(again, 400);
          }
        }
      }
    }
    if (o.tint === false) return true;
    // Per element rather than one token for the surface, which is the same
    // guarantee home's dwell token buys and a narrower one: a second landing
    // elsewhere cannot clear this one's tint, and a second landing on THIS
    // element restarts its own dwell instead of racing an older timer.
    const on = o.current === false ? MARK_REST : MARK;
    clearTimeout(timers.get(el));
    el.classList.remove(...MARK, ...MARK_REST);
    el.classList.add(...FADE, ...on);
    timers.set(el, setTimeout(() => el.classList.remove(...on), o.dwell ?? DWELL));
    return true;
  }

  // ── For a mark that is NOT a node in the flow ────────────────────────────
  //
  // pdf.js's third lesson, and it is why a PDF mark cannot simply wear MARK: a
  // rectangle sized from the text layer sits OVER the glyphs it covers, so it
  // has to multiply against them rather than paint on top of them. That is the
  // "highlighter, not a selection" rule home states for its appendix mark,
  // implemented.
  //
  // And it needs a stronger percentage for the same reason. Multiplying against
  // a white page washes a tint out; the same number that reads clearly behind
  // DOM text on the app's own ground reads as nothing over print. Both pages
  // that draw one arrived at a higher number independently (home's appendix
  // mark at 42, pdf.js's find at 62), which is the substrate talking.
  const OVERLAY = 'position:absolute;pointer-events:none;border-radius:2px;mix-blend-mode:multiply;';
  //
  // `tint(30)` and the utility `bg-warning/30` compute to the same value, not
  // merely a similar one: measured in the app on 2026-09-04, both resolve to
  // oklab(0.89172 0.0143011 0.0426671 / 0.3). So the flow mark and the overlay
  // mark are one colour function read two ways, and a theme change moves both.
  const tint = (pct) => `color-mix(in oklab, var(--color-warning) ${pct}%, transparent)`;
  const FLOW = { current: 30, rest: 10 };   // behind live text
  const PAGE = { current: 45, rest: 25 };   // over a rendered page

  window.Land = { mark, clear, scrollerOf, tint,
                  LAND_AT, DWELL, MARK, MARK_REST, FADE, OVERLAY, FLOW, PAGE };
})();
