#!/usr/bin/env python3
# Generate docs/MERGE-GUIDE.md from merged PR bodies. The PR body's guide
# region (the <!-- guide --> managed block, or, for older PRs, the structural
# ⭐/🥏 Look ... Notes span) is the editable source of shipped history; this
# projects it into one newest-on-top file that survives offline.
#
# Portable: python3, stdlib only, zero dependencies.
# Canonical source: mehrlander/web-tools at scripts/build-merge-guide.py
#
# Non-destructive by default: existing MERGE-GUIDE.md entries are preserved,
# and a generated entry is only ADDED for a PR the file does not already
# cover. Pass --refresh to let generated entries overwrite same-PR entries
# (the mode the retroactive backfill will use once old PR bodies carry proper
# guide regions; tracker task 0009). Entries predating any PR (the #TBD /
# branch-keyed ones) are always preserved verbatim.
#
# Usage:
#   python3 scripts/build-merge-guide.py [owner/repo] [--out FILE]
#           [--from-json FILE] [--since N] [--refresh]
#
#   owner/repo     default mehrlander/web-tools
#   --out FILE     default docs/MERGE-GUIDE.md; existing entries are merged in
#   --from-json F  read the PR list from F instead of the API (a JSON array of
#                  PR objects shaped like the REST pulls endpoint); lets the
#                  generator run offline or against MCP-fetched data
#   --since N      only consider PRs with number >= N (bounds an API walk)
#   --refresh      regenerate entries for covered PRs, not only missing ones
#
# API access (live fetch) reads GH_TOKEN / GITHUB_TOKEN from the environment
# for rate limit and private repos; the projection stays a committed file.

import sys, os, re, json, html, urllib.request

OWNER_REPO = 'mehrlander/web-tools'
OUT = 'docs/MERGE-GUIDE.md'

# ── PR fetch ────────────────────────────────────────────────────────────────

def fetch_prs(owner_repo, since=None):
    tok = os.environ.get('GH_TOKEN') or os.environ.get('GITHUB_TOKEN')
    out, page = [], 1
    while True:
        url = (f'https://api.github.com/repos/{owner_repo}/pulls'
               f'?state=closed&per_page=100&page={page}&sort=created&direction=desc')
        req = urllib.request.Request(url, headers={'Accept': 'application/vnd.github+json'})
        if tok:
            req.add_header('Authorization', 'Bearer ' + tok)
        batch = json.load(urllib.request.urlopen(req, timeout=30))
        if not batch:
            break
        out.extend(batch)
        # Newest-first, so once we pass the --since floor we can stop.
        if since is not None and any((p.get('number') or 0) < since for p in batch):
            break
        page += 1
        if page > 20:  # 2000-PR backstop
            break
    return out

def merged(prs):
    return [p for p in prs if p.get('merged_at')]

# ── Guide-region extraction ─────────────────────────────────────────────────

MARK_OPEN, MARK_CLOSE = '<!-- guide -->', '<!-- /guide -->'
# A body's trailing session footer, cut before it reaches the guide.
FOOTER_RE = re.compile(
    r'^\s*(?:🤖 Generated with|---\s*$|_Generated by|Co-Authored-By:|Claude-Session:|https://claude\.ai/code/session)',
    re.M)
# The first curated line: a ⭐/🥏/📦 Look/Result, or a **Bold heading:**.
LOOK_RE = re.compile(r'^\s*(?:⭐|🥏|📦)', re.M)
BOLD_RE = re.compile(r'^\s*\*\*[^*]+\*\*', re.M)
# Forward-looking sections that belong to the branch, not shipped history.
DROP_SECTION_RE = re.compile(r'^\s*\*\*(?:Next steps|Follow-ups?|Open threads)\b', re.I)

def _cut_footer(text):
    m = FOOTER_RE.search(text)
    return text[:m.start()] if m else text

def extract(body):
    """Return (lead, region) markdown, or (None, None) if the body has no
    curated content (an old terse PR). lead is the one-line outcome; region is
    the ⭐/Changed/Notes block."""
    body = (body or '').replace('\r\n', '\n')
    if MARK_OPEN in body and MARK_CLOSE in body:
        inner = body.split(MARK_OPEN, 1)[1].split(MARK_CLOSE, 1)[0].strip()
        lead = body.split(MARK_OPEN, 1)[0].strip()
        return (_first_para(lead), inner)
    # Structural fallback: lead paragraph, then from the first ⭐/🥏 (or first
    # bold heading) to before the footer.
    trimmed = _cut_footer(body)
    m = LOOK_RE.search(trimmed) or BOLD_RE.search(trimmed)
    if not m:
        return (None, None)
    lead = _first_para(trimmed[:m.start()])
    region = trimmed[m.start():].strip()
    return (lead, region)

def _first_para(text):
    for para in re.split(r'\n\s*\n', text.strip()):
        p = para.strip()
        if p:
            return p
    return ''

def strip_dropped_sections(region):
    """Remove Next steps / Follow-ups blocks: from the heading to the next
    **bold heading** or end."""
    lines = region.split('\n')
    out, skip = [], False
    for ln in lines:
        if DROP_SECTION_RE.match(ln):
            skip = True
            continue
        if skip:
            if BOLD_RE.match(ln):   # next section starts
                skip = False
            else:
                continue
        out.append(ln)
    return re.sub(r'\n{3,}', '\n\n', '\n'.join(out)).strip()

def rewrite_urls(text, head_ref):
    """Point branch blob/tree URLs at main; the branch is deleted after merge."""
    if not head_ref:
        return text
    hr = re.escape(head_ref)
    text = re.sub(r'(/blob/)' + hr + r'(/)', r'\1main\2', text)
    text = re.sub(r'(/tree/)' + hr + r'(/)', r'\1main\2', text)
    return text

# ── Entry model ─────────────────────────────────────────────────────────────

HEADER_RE = re.compile(r'^##\s+(\d{4}-\d{2}-\d{2})?\s*(.*?)\s*(?:\(PR #(\d+)\))?\s*$')

def parse_existing(md):
    """Split an existing MERGE-GUIDE.md into entry blocks. Returns a list of
    {pr, date, text}. The leading preamble (before the first '## ') is dropped;
    a fresh banner is emitted on render."""
    blocks, cur = [], None
    for line in md.split('\n'):
        if line.startswith('## '):
            if cur is not None:
                blocks.append(cur)
            m = HEADER_RE.match(line)
            date = (m.group(1) or '') if m else ''
            pr = int(m.group(3)) if (m and m.group(3)) else None
            cur = {'pr': pr, 'date': date, 'lines': [line]}
        elif cur is not None:
            cur['lines'].append(line)
    if cur is not None:
        blocks.append(cur)
    for b in blocks:
        b['text'] = '\n'.join(b['lines']).rstrip()
        del b['lines']
    return blocks

def build_entry(pr):
    n = pr.get('number')
    date = (pr.get('merged_at') or '')[:10]
    title = html.unescape(pr.get('title') or '').strip()
    head_ref = ((pr.get('head') or {}).get('ref')) or ''
    lead, region = extract(pr.get('body'))
    if region is None:
        return None  # terse body, nothing curated to project
    region = strip_dropped_sections(rewrite_urls(html.unescape(region), head_ref))
    lead = rewrite_urls(html.unescape(lead or ''), head_ref).strip()
    parts = [f'## {date} {title} (PR #{n})']
    if lead:
        parts.append('')
        parts.append(lead)
    if region:
        parts.append('')
        parts.append(region)
    parts.append('')
    parts.append(f'[PR #{n}](https://github.com/{OWNER_REPO}/pull/{n})')
    return {'pr': n, 'date': date, 'text': '\n'.join(parts).rstrip()}

# ── Merge + render ──────────────────────────────────────────────────────────

BANNER = (
    "# Merge guide\n\n"
    "Newest-on-top log of what each session shipped, generated from merged PR\n"
    "bodies by `scripts/build-merge-guide.py`. A PR body's guide region is the\n"
    "editable source; do not hand-edit entries below. Regenerate:\n\n"
    "    python3 scripts/build-merge-guide.py " + OWNER_REPO + " --out " + OUT + "\n\n"
    "Entries predating the generator were hand-authored and are preserved until\n"
    "backfilled (tracker task 0009).\n\n"
    "---\n"
)

def merge_entries(existing, generated, refresh):
    by_pr = {}
    order = []
    for e in existing:
        key = ('pr', e['pr']) if e['pr'] is not None else ('raw', len(order))
        by_pr[key] = e
        order.append(key)
    added = refreshed = 0
    for g in generated:
        key = ('pr', g['pr'])
        if key in by_pr:
            if refresh:
                by_pr[key] = g
                refreshed += 1
            # else: preserve the existing curated entry
        else:
            by_pr[key] = g
            order.append(key)
            added += 1
    entries = [by_pr[k] for k in order]
    # Newest-first by date; stable for equal/blank dates.
    entries.sort(key=lambda e: e['date'] or '0000-00-00', reverse=True)
    return entries, added, refreshed

def render(entries):
    return BANNER + '\n' + '\n\n'.join(e['text'] for e in entries) + '\n'

# ── Main ────────────────────────────────────────────────────────────────────

def main(argv):
    global OWNER_REPO
    owner_repo = OWNER_REPO
    out = OUT
    from_json = None
    since = None
    refresh = False
    rest = []
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == '--out': out = argv[i + 1]; i += 2
        elif a == '--from-json': from_json = argv[i + 1]; i += 2
        elif a == '--since': since = int(argv[i + 1]); i += 2
        elif a == '--refresh': refresh = True; i += 1
        else: rest.append(a); i += 1
    if rest:
        owner_repo = rest[0]
    OWNER_REPO = owner_repo

    if from_json:
        with open(from_json) as f:
            prs = json.load(f)
    else:
        prs = fetch_prs(owner_repo, since)
    prs = merged(prs)
    if since is not None:
        prs = [p for p in prs if (p.get('number') or 0) >= since]

    generated = [e for e in (build_entry(p) for p in prs) if e]

    existing = []
    if os.path.exists(out):
        with open(out) as f:
            existing = parse_existing(f.read())

    entries, added, refreshed = merge_entries(existing, generated, refresh)
    text = render(entries)
    with open(out, 'w') as f:
        f.write(text)

    kept = len(entries) - added
    print(f'merge-guide: {len(entries)} entries '
          f'({added} added, {refreshed} refreshed, {kept} preserved) -> {out}',
          file=sys.stderr)

if __name__ == '__main__':
    main(sys.argv[1:])
