#!/usr/bin/env node
// Build a self-resolving offline form of a page's gh.load chain — "the build".
//
//   node tools/build.mjs <page-path>            -> dist/<page>.js
//
// The emit format lives in lib/kits/build.js (window.buildKit.emit), shared with
// the in-browser baker (kits/bundle.js) so the two can't drift. This Node entry
// supplies a statically-walked cache (tools/lib/graph.mjs) and writes dist/.
//
// What it emits is NOT a rewritten graph: it's the real gh-api.js loader with
// GH.prototype.get overridden by an inlined cache of every own-repo file the page
// reaches. The actual loader runs — same strip+wrap+execute, gh-boot registry,
// read() tracking — only the source bytes come from memory. Third-party libs stay
// on the page's CDN tags.
//
// The build and the runtime loader optimize opposite things: the loader is the
// fresh, per-file dev/review path; the build is a delivery snapshot. So a page
// adopts the build only at a boundary (baked into a downloadable page, or a
// versioned same-origin asset) — never back onto jsDelivr, whose cache the loader
// was written to avoid.
//
// dist/ is generated (gitignored); rebuild on demand.

import { readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildGraph } from './lib/graph.mjs';
import { loadKit } from './lib/kit-shim.mjs';

const REPO = 'mehrlander/web-tools';
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const arg = process.argv[2];
if (!arg) {
  console.error('Usage: node tools/build.mjs <page-path>');
  process.exit(2);
}

let graph;
try {
  graph = buildGraph(repoRoot, arg);
} catch (e) {
  console.error(`build: ${e.message}`);
  process.exit(1);
}

const { buildKit } = loadKit(repoRoot, 'lib/kits/build.js');
const ghApiSrc = await readFile(path.join(repoRoot, 'lib/gh-api.js'), 'utf8');

// graph.files -> the { 'lib/<path>': source } cache buildKit.emit expects.
const cache = Object.fromEntries(graph.files.map(f => [f.key, f.src]));

const baseName = path.basename(arg, path.extname(arg));
const built = new Date().toISOString().slice(0, 10);
const header = `// dist/${baseName}.js — generated by tools/build.mjs on ${built}. Do not edit.
// Offline form of ${arg}'s gh.load chain (the gh-api.js loader + an inlined source
// cache). Third-party libs stay on their CDN tags. Rebuild: node tools/build.mjs ${arg}

`;

const out = buildKit.emit({ ghApiSrc, cache, repo: REPO, defaultRef: graph.defaultRef, header });

const distDir = path.join(repoRoot, 'dist');
await mkdir(distDir, { recursive: true });
const outPath = path.join(distDir, `${baseName}.js`);
await writeFile(outPath, out);

const kb = (Buffer.byteLength(out) / 1024).toFixed(0);
console.log(`build: ${arg}`);
console.log(`  seeds (${graph.seeds.length}): ${graph.seeds.join(', ')}`);
console.log(`  cached own-code files (${graph.files.length}):`);
for (const f of graph.files.sort((a, b) => a.rel.localeCompare(b.rel))) {
  console.log(`    ${f.rel}  (${(f.src.length / 1024).toFixed(1)}k)`);
}
if (graph.misses.length) console.log(`  misses (not on disk): ${graph.misses.join(', ')}`);
console.log(`  -> ${path.relative(repoRoot, outPath)}  (${kb}k)`);
